name: Build

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup frontend
        run: yarn
      - name: Lint frontend
        run: yarn lint
      - name: Build frontend
        run: yarn build

      - name: Setup functions
        working-directory: ./functions
        run: yarn
      - name: Lint functions
        working-directory: ./functions
        run: yarn lint
      - name: Build functions
        working-directory: ./functions
        run: yarn build

      - name: Check format
        run: yarn format:check

      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: yarn e2e
